name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: "Build & Push Docker Image"
        run: |
          docker build --no-cache --build-arg FILEPATH=${{ secrets.FILEPATH }} -t deepanshudks/quicklink:latest .
          # docker push deepanshudks/quicklink:latest                 
        # uses: docker/build-push-action@v2
        # with: 
        #   context: .
        #   file: ./Dockerfile
        #   push: true
        #   no-cache: true
        #   build-args: |
        #     "FILEPATH=${{ secrets.FILEPATH }}"
        #   tags: deepanshudks/quicklink:latest

      - name: Verify Pushed Image
        run: docker pull deepanshudks/quicklink:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo docker pull deepanshudks/quicklink:latest
            
            sudo docker stop quicklinkbackend || true
            sudo docker rm quicklinkbackend || true
            sudo docker system prune -af
            
            # Create .env file with secrets on EC2
            cat <<EOF > ~/quicklink.env
            DATABASE_URL=${{ secrets.DATABASE_URL }}
            NODE_ENV=${{ secrets.NODE_ENV }}
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_REGION=${{ secrets.AWS_REGION }}
            AWS_BUCKET_NAME=${{ secrets.AWS_BUCKET_NAME }}
            AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            EOF
            

            sudo docker run -d --name quicklinkbackend \
              --env-file ~/quicklink.env \
              --restart always \
              -p 5000:5000 deepanshudks/quicklink:latest
