name: "Build and deploy frontend"

on: 
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build & Push Docker Image
        run: docker build --no-cache --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} -t deepanshudks/quicklinkreact  .

      - name: Publish Image to docker hub
        run: docker push deepanshudks/quicklinkreact:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            
            sudo docker stop quicklinkreact || true
            sudo docker rm quicklinkreact || true
            sudo docker pull deepanshudks/quicklinkreact:latest
            
            sudo docker run -d --name quicklinkreact --restart always -p 3000:80 deepanshudks/quicklinkreact:latest